<script setup lang="ts">
import {computed,reactive,ref,watch} from 'vue'
import {GitBranch,Plus,X} from 'lucide-vue-next'
import type {WorkflowNode} from '../types'
const props=defineProps<{createOpen:boolean;branchNode:WorkflowNode|null}>();const emit=defineEmits<{closeCreate:[];createProject:[body:Record<string,unknown>];closeBranch:[];createBranch:[body:Record<string,unknown>]}>();const project=reactive({name:'',customer_name:'',brand_name:'',event_type:'',description:''}),branchName=ref('');watch(()=>props.branchNode,(node)=>{branchName.value=node?`${node.title} · 新方案`:''});const projectValid=computed(()=>Boolean(project.name.trim()))
/** 提交新项目并清理本地表单。 */
function submitProject():void{if(!projectValid.value)return;emit('createProject',{...project,metadata:{}});Object.assign(project,{name:'',customer_name:'',brand_name:'',event_type:'',description:''})}
/** 提交历史节点分支创建请求。 */
function submitBranch():void{if(!props.branchNode||!branchName.value.trim())return;emit('createBranch',{source_node_id:props.branchNode.node_id,branch_name:branchName.value.trim(),expected_result_version:props.branchNode.result_version})}
</script>
<template><div v-if="createOpen" class="modal-backdrop" @mousedown.self="emit('closeCreate')"><section class="modal" role="dialog" aria-modal="true" aria-label="创建项目"><header><div><span class="modal-icon"><Plus :size="18"/></span><div><h2>新建策划项目</h2><p>创建后从“项目准备”阶段开始。</p></div></div><button class="icon-button" type="button" title="关闭" @click="emit('closeCreate')"><X :size="18"/></button></header><div class="form-grid"><label class="full">项目名称<input v-model="project.name" autofocus placeholder="例如：2026 夏季品牌发布会"/></label><label>客户名称<input v-model="project.customer_name" placeholder="客户或业务方"/></label><label>品牌名称<input v-model="project.brand_name" placeholder="活动品牌"/></label><label class="full">活动类型<input v-model="project.event_type" placeholder="发布会、展览、论坛、年会…"/></label><label class="full">项目说明<textarea v-model="project.description" rows="4" placeholder="简要描述项目背景和当前目标"/></label></div><footer><button class="secondary" type="button" @click="emit('closeCreate')">取消</button><button class="primary" type="button" :disabled="!projectValid" @click="submitProject">创建项目</button></footer></section></div><div v-if="branchNode" class="modal-backdrop" @mousedown.self="emit('closeBranch')"><section class="modal compact-modal" role="dialog" aria-modal="true" aria-label="创建方案分支"><header><div><span class="modal-icon coral"><GitBranch :size="18"/></span><div><h2>从历史节点创建分支</h2><p>原方案不会被覆盖，新分支使用独立 Agent 会话。</p></div></div><button class="icon-button" type="button" title="关闭" @click="emit('closeBranch')"><X :size="18"/></button></header><div class="source-node"><span>来源节点</span><strong>{{branchNode.title}}</strong><small>{{branchNode.summary||'已有阶段结果'}} · v{{branchNode.result_version}}</small></div><label>分支名称<input v-model="branchName" autofocus/></label><footer><button class="secondary" type="button" @click="emit('closeBranch')">取消</button><button class="primary coral-button" type="button" :disabled="!branchName.trim()" @click="submitBranch">创建并切换</button></footer></section></div></template>