JOB_DEFAULT_PAGE = 1
JOB_DEFAULT_PAGE_SIZE = 20
JOB_MAX_PAGE_SIZE = 100

JOB_STATUS_RECRUITING = "recruiting"
JOB_STATUS_MAYBE_CLOSED = "maybe_closed"
JOB_STATUS_CLOSED = "closed"

SPIDER_RUN_STATUS_RUNNING = "running"
SPIDER_RUN_STATUS_SUCCESS = "success"
SPIDER_RUN_STATUS_FAILED = "failed"
